# -*- coding: utf-8 -*-
"""House price.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ycZ_HMX7-TeGetR6y9oUm13AMcZsc1Ht
"""

from google.colab import files
Upload = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv("USA_Housing.csv")

# Printing first 5 records of the dataset
print(dataset.head(5))

dataset.shape

obj = (dataset.dtypes == 'object')
object_cols = list(obj[obj].index)
print("Categorical variables:",len(object_cols))

int_ = (dataset.dtypes == 'int')
num_cols = list(int_[int_].index)
print("Integer variables:",len(num_cols))

fl = (dataset.dtypes == 'float')
fl_cols = list(fl[fl].index)
print("Float variables:",len(fl_cols))

plt.figure(figsize=(12, 6))
sns.heatmap(dataset.corr(),
            cmap = 'BrBG',
            fmt = '.2f',
            linewidths = 2,
            annot = True)